//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "caretakers_dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub caretaker_id: Uuid,
    pub dog_id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::caretakers::Entity",
        from = "Column::CaretakerId",
        to = "super::caretakers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Caretakers,
    #[sea_orm(
        belongs_to = "super::dogs::Entity",
        from = "Column::DogId",
        to = "super::dogs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dogs,
}

impl Related<super::caretakers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Caretakers.def()
    }
}

impl Related<super::dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::caretakers::Entity")]
    Caretakers,
    #[sea_orm(entity = "super::dogs::Entity")]
    Dogs,
}
