//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub breed: String,
    pub gender: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::caretakers_dogs::Entity")]
    CaretakersDogs,
    #[sea_orm(has_many = "super::walk_dogs::Entity")]
    WalkDogs,
}

impl Related<super::caretakers_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CaretakersDogs.def()
    }
}

impl Related<super::walk_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkDogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::caretakers_dogs::Entity")]
    CaretakersDogs,
    #[sea_orm(entity = "super::walk_dogs::Entity")]
    WalkDogs,
}
