//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod caretakers;
pub mod caretakers_dogs;
pub mod dogs;
pub mod sea_orm_active_enums;
pub mod walk_dogs;
pub mod walk_events;
pub mod walk_photos;
pub mod walks;

seaography::register_entity_modules!([
    caretakers,
    caretakers_dogs,
    dogs,
    walk_dogs,
    walk_events,
    walk_photos,
    walks,
]);
seaography::register_active_enums!([sea_orm_active_enums::EventType,]);
