//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub caretaker_id: Uuid,
    pub started_at: DateTime,
    pub ended_at: Option<DateTime>,
    pub distance: Option<i32>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::caretakers::Entity",
        from = "Column::CaretakerId",
        to = "super::caretakers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Caretakers,
    #[sea_orm(has_many = "super::walk_dogs::Entity")]
    WalkDogs,
    #[sea_orm(has_many = "super::walk_photos::Entity")]
    WalkPhotos,
}

impl Related<super::caretakers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Caretakers.def()
    }
}

impl Related<super::walk_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkDogs.def()
    }
}

impl Related<super::walk_photos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkPhotos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::caretakers::Entity")]
    Caretakers,
    #[sea_orm(entity = "super::walk_dogs::Entity")]
    WalkDogs,
    #[sea_orm(entity = "super::walk_photos::Entity")]
    WalkPhotos,
}
