//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::EventType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "walk_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub walk_dog_id: Uuid,
    pub event: EventType,
    pub occurred_at: DateTime,
    #[sea_orm(column_type = "Double")]
    pub latitude: f64,
    #[sea_orm(column_type = "Double")]
    pub longitude: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::walk_dogs::Entity",
        from = "Column::WalkDogId",
        to = "super::walk_dogs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WalkDogs,
}

impl Related<super::walk_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkDogs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::walk_dogs::Entity")]
    WalkDogs,
}
