//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub breed: String,
    pub gender: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub caretakers_dogs: HasMany<super::caretakers_dogs::Entity>,
    #[sea_orm(has_many)]
    pub walk_dogs: HasMany<super::walk_dogs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
