//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub caretaker_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
    pub distance: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "caretaker_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub caretakers: HasOne<super::caretakers::Entity>,
    #[sea_orm(has_many)]
    pub walk_dogs: HasMany<super::walk_dogs::Entity>,
    #[sea_orm(has_many)]
    pub walk_photos: HasMany<super::walk_photos::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
