//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walk_dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_walk_dogs_walk_id_dog_id")]
    pub walk_id: Uuid,
    #[sea_orm(unique_key = "idx_walk_dogs_walk_id_dog_id")]
    pub dog_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "dog_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub dogs: HasOne<super::dogs::Entity>,
    #[sea_orm(has_many)]
    pub walk_events: HasMany<super::walk_events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "walk_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub walks: HasOne<super::walks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
