//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub name: String,
    pub breed: Option<String>,
    pub gender: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub birth_date: Option<Json>,
    pub photo_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::walk_dogs::Entity")]
    WalkDogs,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::walk_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkDogs.def()
    }
}

impl Related<super::walks::Entity> for Entity {
    fn to() -> RelationDef {
        super::walk_dogs::Relation::Walks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::walk_dogs::Relation::Dogs.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::users::Entity")]
    Users,
    #[sea_orm(entity = "super::walk_dogs::Entity")]
    WalkDogs,
    #[sea_orm(entity = "super::walks::Entity")]
    Walks,
}
