//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod dogs;
pub mod users;
pub mod walk_dogs;
pub mod walks;

/// Register all entities for GraphQL queries (mutations are handled by custom resolvers).
pub fn register_entity_modules(mut builder: seaography::Builder) -> seaography::Builder {
    seaography::register_entity!(builder, dogs, mutation: false);
    seaography::register_entity!(builder, users, mutation: false);
    seaography::register_entity!(builder, walk_dogs, mutation: false);
    seaography::register_entity!(builder, walks, mutation: false);
    builder
}
