//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::dogs::Entity as Dogs;
pub use super::users::Entity as Users;
pub use super::walk_dogs::Entity as WalkDogs;
pub use super::walks::Entity as Walks;
