//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub status: String,
    pub distance_m: Option<i32>,
    pub duration_sec: Option<i32>,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::walk_dogs::Entity")]
    WalkDogs,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::walk_dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalkDogs.def()
    }
}

impl Related<super::dogs::Entity> for Entity {
    fn to() -> RelationDef {
        super::walk_dogs::Relation::Dogs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::walk_dogs::Relation::Walks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn walk_status_active_to_string() {
        assert_eq!(WalkStatus::Active.to_string(), "active");
    }

    #[test]
    fn walk_status_finished_to_string() {
        assert_eq!(WalkStatus::Finished.to_string(), "finished");
    }

    #[test]
    fn walk_status_from_str_active() {
        let s: WalkStatus = "active".parse().unwrap();
        assert_eq!(s, WalkStatus::Active);
    }

    #[test]
    fn walk_status_from_str_finished() {
        let s: WalkStatus = "finished".parse().unwrap();
        assert_eq!(s, WalkStatus::Finished);
    }

    #[test]
    fn walk_status_from_str_invalid_returns_error() {
        let result: Result<WalkStatus, _> = "pending".parse();
        assert!(result.is_err());
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::users::Entity")]
    Users,
    #[sea_orm(entity = "super::walk_dogs::Entity")]
    WalkDogs,
    #[sea_orm(entity = "super::dogs::Entity")]
    Dogs,
}
