include classpath("application.conf")

node-address {
  protocol = http
  host = elasticmq
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

aws {
  region = ap-northeast-1
  accountId = "000000000000"
}

queues {
  "track-point-local-dlq" {
    defaultVisibilityTimeout = 60 seconds
    messageRetentionPeriod = 4 days
  }
  "track-point-local" {
    defaultVisibilityTimeout = 60 seconds
    messageRetentionPeriod = 4 days
    deadLettersQueue {
      name = "track-point-local-dlq"
      maxReceiveCount = 5
    }
  }
}
