//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "caretakers_dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub caretaker_id: Uuid,
    pub dog_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "caretaker_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub caretakers: HasOne<super::caretakers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "dog_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub dogs: HasOne<super::dogs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
