//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "caretakers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    pub avatar: Option<String>,
    #[sea_orm(unique)]
    pub cognito_sub: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub caretakers_dogs: HasMany<super::caretakers_dogs::Entity>,
    #[sea_orm(has_many)]
    pub walks: HasMany<super::walks::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
