//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::entity::{birthday, sea_orm_active_enums::GenderType, user_dog, walk_dog};

// use super::sea_orm_active_enums::GenderType;
use sea_orm::{ActiveValue::Set, entity::prelude::*};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub breed: Option<String>,
    pub gender: GenderType,
    pub avatar: Option<String>,
    pub birthday: Option<birthday::Model>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub user_dogs: HasMany<user_dog::Entity>,
    #[sea_orm(has_many)]
    pub walk_dogs: HasMany<walk_dog::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            ..ActiveModelTrait::default()
        }
    }
}
