//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::GenderType;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "dog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub breed: Option<String>,
    pub gender: GenderType,
    pub avatar: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub user_dogs: HasMany<super::user_dog::Entity>,
    #[sea_orm(has_many)]
    pub walk_dogs: HasMany<super::walk_dog::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
