//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod dog;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_dog;
pub mod walk;
pub mod walk_dog;
pub mod walk_event;
pub mod walk_photo;
