//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod caretakers;
pub mod caretakers_dogs;
pub mod dogs;
pub mod sea_orm_active_enums;
pub mod walk_dogs;
pub mod walk_events;
pub mod walk_photos;
pub mod walks;
