//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::caretakers::Entity as Caretakers;
pub use super::caretakers_dogs::Entity as CaretakersDogs;
pub use super::dogs::Entity as Dogs;
pub use super::walk_dogs::Entity as WalkDogs;
pub use super::walk_events::Entity as WalkEvents;
pub use super::walk_photos::Entity as WalkPhotos;
pub use super::walks::Entity as Walks;
