//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::dog::Entity as Dog;
pub use super::user::Entity as User;
pub use super::user_dog::Entity as UserDog;
pub use super::walk::Entity as Walk;
pub use super::walk_dog::Entity as WalkDog;
pub use super::walk_dog_event::Entity as WalkDogEvent;
pub use super::walk_photo::Entity as WalkPhoto;
