//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{ActiveValue::Set, entity::prelude::*};

use crate::entity::{user_dog, walk};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: Option<String>,
    pub avatar: Option<String>,
    #[sea_orm(unique)]
    pub cognito_sub: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub user_dogs: HasMany<user_dog::Entity>,
    #[sea_orm(has_many)]
    pub walks: HasMany<walk::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            ..ActiveModelTrait::default()
        }
    }
}
