//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::{ActiveValue::Set, entity::prelude::*};

use crate::entity::{dog, walk, walk_dog_event};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walk_dog")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_walk_dog_walk_id_dog_id")]
    pub walk_id: Uuid,
    #[sea_orm(unique_key = "idx_walk_dog_walk_id_dog_id")]
    pub dog_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "dog_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub dog: HasOne<dog::Entity>,
    #[sea_orm(
        belongs_to,
        from = "walk_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub walk: HasOne<walk::Entity>,
    #[sea_orm(has_many)]
    pub walk_dog_events: HasMany<walk_dog_event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            ..ActiveModelTrait::default()
        }
    }
}
