//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use anyhow::Result;
use sea_orm::{ActiveValue::Set, ExprTrait, QuerySelect, entity::prelude::*};

use crate::entity::{track_point, user, walk, walk_dog, walk_photo};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub started_at: DateTimeWithTimeZone,
    pub ended_at: Option<DateTimeWithTimeZone>,
    pub distance: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user: HasOne<user::Entity>,
    #[sea_orm(has_many)]
    pub walk_dogs: HasMany<walk_dog::Entity>,
    #[sea_orm(has_many)]
    pub walk_photos: HasMany<walk_photo::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::now_v7()),
            ..ActiveModelTrait::default()
        }
    }
}

impl Model {
    pub async fn points(
        &self,
        dynamo_client: &aws_sdk_dynamodb::Client,
    ) -> Result<Vec<track_point::Model>> {
        track_point::Model::find_all_by_walk_id(dynamo_client, self.id).await
    }
}

impl Entity {
    pub async fn aggregate(
        db: &DatabaseConnection,
        query: Select<Self>,
    ) -> Result<(i64, i64, i64)> {
        let (total_count, total_distance, total_duration): (i64, i64, i64) = query
            .select_only()
            .column_as(Expr::col(walk::Column::Id).count(), "total_count")
            .column_as(
                Expr::cust("COALESCE(SUM(distance), 0)::bigint"),
                "total_distance",
            )
            .column_as(
                Expr::cust("COALESCE(SUM(EXTRACT(EPOCH FROM (ended_at - started_at))), 0)::bigint"),
                "total_duration",
            )
            .into_tuple()
            .one(db)
            .await?
            .unwrap_or_default();
        Ok((total_count, total_distance, total_duration))
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use sea_orm::{ColumnTrait, DatabaseBackend, EntityTrait, MockDatabase, QueryFilter, Value};
    use uuid::Uuid;

    use super::*;

    fn aggregate_row(
        total_count: i64,
        total_distance: i64,
        total_duration: i64,
    ) -> BTreeMap<&'static str, Value> {
        BTreeMap::from([
            ("total_count", total_count.into()),
            ("total_distance", total_distance.into()),
            ("total_duration", total_duration.into()),
        ])
    }

    #[tokio::test]
    async fn aggregate_coalesces_nullable_sums_to_zero() {
        let user_id = Uuid::parse_str("019e0dc4-066b-7a22-b755-969ee6beb5e9").unwrap();
        let db = MockDatabase::new(DatabaseBackend::Postgres)
            .append_query_results([[aggregate_row(0, 0, 0)]])
            .into_connection();
        let query = Entity::find().filter(Column::UserId.eq(user_id));

        let aggregate = Entity::aggregate(&db, query).await.unwrap();

        assert_eq!(aggregate, (0, 0, 0));
        let log = db.into_transaction_log();
        let sql = log
            .iter()
            .flat_map(|entry| entry.statements())
            .map(|statement| statement.sql.as_str())
            .collect::<Vec<_>>()
            .join("\n");
        assert!(sql.contains("COALESCE(SUM(distance), 0)::bigint"));
        assert!(sql.contains("COALESCE(SUM(EXTRACT(EPOCH FROM (ended_at - started_at))), 0)::bigint"));
    }
}
