//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod dog_invitations;
pub mod dog_members;
pub mod dogs;
pub mod encounters;
pub mod friendships;
pub mod users;
pub mod walk_dogs;
pub mod walk_events;
pub mod walks;

/// Register all entities for GraphQL queries (mutations are handled by custom resolvers).
pub fn register_entity_modules(builder: seaography::Builder) -> seaography::Builder {
    // All queries are handled by custom resolvers with proper authorization checks.
    // Seaography auto-generated queries are disabled to prevent data exposure.
    builder
}
