//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub cognito_sub: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub encounter_detection_enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::walks::Entity")]
    Walks,
    #[sea_orm(has_many = "super::dog_members::Entity")]
    DogMembers,
}

impl Related<super::walks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Walks.def()
    }
}

impl Related<super::dog_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DogMembers.def()
    }
}

impl Related<super::dogs::Entity> for Entity {
    fn to() -> RelationDef {
        super::dog_members::Relation::Dogs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::dog_members::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::walks::Entity")]
    Walks,
    #[sea_orm(entity = "super::dog_members::Entity")]
    DogMembers,
    #[sea_orm(entity = "super::dogs::Entity")]
    Dogs,
}
