//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "walk_dogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub walk_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dog_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dogs::Entity",
        from = "Column::DogId",
        to = "super::dogs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dogs,
    #[sea_orm(
        belongs_to = "super::walks::Entity",
        from = "Column::WalkId",
        to = "super::walks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Walks,
}

impl Related<super::dogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dogs.def()
    }
}

impl Related<super::walks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Walks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::dogs::Entity")]
    Dogs,
    #[sea_orm(entity = "super::walks::Entity")]
    Walks,
}
