export const DEFAULT_DAILY_GOAL_MINUTES = 30;
export const MIN_DAILY_GOAL_MINUTES = 10;
export const MAX_DAILY_GOAL_MINUTES = 120;
export const DAILY_GOAL_STEP_MINUTES = 5;
export const DAILY_GOAL_CYCLE_DAYS = 1;
export const WEEKLY_GOAL_CYCLE_DAYS = 7;
export const MIN_WEEKLY_GOAL_MINUTES = MIN_DAILY_GOAL_MINUTES * WEEKLY_GOAL_CYCLE_DAYS;
export const MAX_WEEKLY_GOAL_MINUTES = MAX_DAILY_GOAL_MINUTES * WEEKLY_GOAL_CYCLE_DAYS;

export type GoalCycleDays = typeof DAILY_GOAL_CYCLE_DAYS | typeof WEEKLY_GOAL_CYCLE_DAYS;
